{
 "title": "Debugging",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "YOUR_NODE_ID" },
   { "name": "cores", "query": "1,2,4,8,16,32,64,128" },
   { "name": "JOBNAME", "label": "job_name", "query": "${VAR_JOBNAME}" }
  ]
 },
 "panels": [
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "arweave_block_height{instance=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VDF Steps Behind",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "block_vdf_advance{instance=\"$node\"}",
     "legendFormat": "Value"
    },
    {
     "expr": "avg_over_time(block_vdf_advance{instance=\"$node\"}[10m])",
     "legendFormat": "Average (10m)"
    }
   ]
  },
  { "title": "Compute Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Message Queue",
   "type": "timeseries",
   "description": "Periodically (every 5000ms) a background process sampler samples which processes are running and captures the message_queue_len",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(process) (process_info{instance=\"$node\", type=\"message_queue\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "CPU Load / # Cores",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{instance=~\"$node\"}[5m])) without (kind) * 100) / $cores",
     "legendFormat": "CPU Load / # Cores"
    },
    {
     "expr": "scheduler_utilization{instance=\"$node\"} * 100",
     "legendFormat": "{{type}} schedulers"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(process_info{instance=\"$node\", type=~\"memory\", process!~\"processes|processes_used|total|system\"}, \"short_process\", \"$1\", \"process\", \"^(.{1,50}).*\")",
     "legendFormat": "{{short_process}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$node\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$node\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "process_max_resident_memory_bytes{instance=~\"$node\"}",
     "legendFormat": "Max Resident"
    },
    {
     "expr": "process_info{instance=\"$node\", type=~\"memory\", process=~\"processes|total\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Reductions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(process) (irate(process_info{instance=\"$node\", type=\"reductions\"}[2m]))",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Binary Allocator Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "allocator{instance=~\"$node\", section=\"mbcs\", metric=\"binary_block_size\"}",
     "legendFormat": "MBCS Block Size"
    },
    {
     "expr": "allocator{instance=~\"$node\", section=\"mbcs\", metric=\"binary_carrier_size\"}",
     "legendFormat": "MBCS Carrier Size"
    },
    {
     "expr": "scalar(allocator{instance=~\"$node\", section=\"mbcs\", metric=\"binary_block_size\"}) / scalar(allocator{instance=~\"$node\", section=\"mbcs\", metric=\"binary_carrier_size\"})",
     "legendFormat": "MBCS Utilization"
    },
    {
     "expr": "allocator{instance=~\"$node\", section=\"sbcs\", metric=\"binary_block_size\"}",
     "legendFormat": "SBCS Block Size"
    },
    {
     "expr": "allocator{instance=~\"$node\", section=\"sbcs\", metric=\"binary_carrier_size\"}",
     "legendFormat": "SBCS Carrier Size"
    },
    {
     "expr": "scalar(allocator{instance=~\"$node\", section=\"sbcs\", metric=\"binary_block_size\"}) / scalar(allocator{instance=~\"$node\", section=\"sbcs\", metric=\"binary_carrier_size\"})",
     "legendFormat": "SBCS Utilization"
    }
   ]
  },
  {
   "title": "Inbound requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total inbound requests (# per second)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum by(http_method, route) (rate(cowboy_requests_total{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Successful inbound requests (# per second)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 8, "y": 44 },
     "targets": [
      {
       "expr": "sum by(http_method, route) (rate(cowboy_requests_total{instance=\"$node\", status_class=\"success\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Failed inbound requests (# per second)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 44 },
     "targets": [
      {
       "expr": "sum by(http_method, route, status_class) (rate(cowboy_requests_total{instance=\"$node\", status_class!=\"success\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}} {{status_class}}"
      }
     ]
    },
    {
     "title": "Total inbound requests (average latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "(sum by(http_method, route) (rate(cowboy_request_duration_seconds_sum{instance=\"$node\"}[5m]))) /\n(sum by(http_method, route) (rate(cowboy_request_duration_seconds_count{instance=\"$node\"}[5m])))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Successful inbound requests (average latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 8, "y": 55 },
     "targets": [
      {
       "expr": "(sum by(http_method, route) (rate(cowboy_request_duration_seconds_sum{instance=\"$node\", status_class=\"success\"}[5m]))) /\n(sum by(http_method, route) (rate(cowboy_request_duration_seconds_count{instance=\"$node\", status_class=\"success\"}[5m])))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Failed inbound requests (average latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 55 },
     "targets": [
      {
       "expr": "(sum by(http_method, route) (rate(cowboy_request_duration_seconds_sum{instance=\"$node\", status_class!=\"success\"}[5m]))) /\n(sum by(http_method, route) (rate(cowboy_request_duration_seconds_count{instance=\"$node\", status_class!=\"success\"}[5m])))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Total inbound requests (total latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum by(http_method, route) (rate(cowboy_request_duration_seconds_sum{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Successful inbound requests (total latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 8, "y": 65 },
     "targets": [
      {
       "expr": "sum by(http_method, route) (rate(cowboy_request_duration_seconds_sum{instance=\"$node\", status_class=\"success\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Failed inbound requests (total latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 65 },
     "targets": [
      {
       "expr": "sum by(http_method, route) (rate(cowboy_request_duration_seconds_sum{instance=\"$node\", status_class!=\"success\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Outbound Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{instance=\"$node\"}[2m])*8)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Outbound Requests (# per second)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method) (rate(ar_http_request_duration_seconds_count{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Successful Requests (# per second)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method) (rate(ar_http_request_duration_seconds_count{instance=\"$node\", status_class=\"success\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Failed Requests (# per second)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method, status_class) (rate(ar_http_request_duration_seconds_count{instance=\"$node\", status_class!=\"success\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}} {{status_class}}"
      }
     ]
    },
    {
     "title": "Total Outbound Requests (average latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method) (rate(ar_http_request_duration_seconds_sum{instance=\"$node\"}[5m])) / sum by(route, http_method) (rate(ar_http_request_duration_seconds_count{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Successful Requests (average latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method) (rate(ar_http_request_duration_seconds_sum{instance=\"$node\", status_class=\"success\"}[5m])) / sum by(route, http_method) (rate(ar_http_request_duration_seconds_count{instance=\"$node\", status_class=\"success\"}[2m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Failed Requests (average latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method, status_class) (rate(ar_http_request_duration_seconds_sum{instance=\"$node\", status_class!=\"success\"}[5m])) / sum by(route, http_method, status_class) (rate(ar_http_request_duration_seconds_count{instance=\"$node\", status_class!=\"success\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}} {{status_class}}"
      }
     ]
    },
    {
     "title": "Total Outbound Requests (total latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method) (rate(ar_http_request_duration_seconds_sum{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Successful Requests (total latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 8, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method) (rate(ar_http_request_duration_seconds_sum{instance=\"$node\", status_class=\"success\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Failed Requests (total latency in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method, status_class) (rate(ar_http_request_duration_seconds_sum{instance=\"$node\", status_class!=\"success\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}} {{status_class}}"
      }
     ]
    }
   ]
  }
 ]
}