{
 "title": "Arweave Syncing/Packing",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({job=\"$JOBNAME\"}, instance)"
    }
   },
   { "name": "JOBNAME", "label": "job_name", "query": "${VAR_JOBNAME}" }
  ]
 },
 "panels": [
  {
   "title": "Total Chunks Written (in bytes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(chunks_stored{instance=\"$node\"}) * 256 * 1000",
     "legendFormat": "Chunks Written"
    }
   ]
  },
  {
   "title": "Partition Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(v2_index_data_size_by_packing{instance=\"$node\"}) by (partition_number, packing)",
     "legendFormat": "{{partition_number}} {{packing}}"
    }
   ]
  },
  {
   "title": "2.9 Entropy Written (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(replica_2_9_entropy_stored{instance=\"$node\"}[2m])",
     "legendFormat": "Write {{store_id}}"
    },
    {
     "expr": "sum(rate(replica_2_9_entropy_stored{instance=\"$node\"}[2m]))",
     "legendFormat": "Write Total"
    }
   ]
  },
  {
   "title": "Sync Requests (# / second)",
   "type": "timeseries",
   "description": "GET /chunk2 requests sent per second to different peers. Each successful request downloads a chunk to your node.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(peer) (rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\"}[2m]))",
     "legendFormat": "{{peer}}"
    },
    {
     "expr": "sum(rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\"}[2m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Chunks Written (bytes / second)",
   "type": "timeseries",
   "description": "Each chunk written is assumed to be 256 KiB.\n\nNote: this may differ from your packing rate as each chunk written may need a different number of packing operations (0 to 2 depending on the format the chunk is received and the format it is written)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(chunks_stored{instance=\"$node\"}[2m]) * 256 * 1024",
     "legendFormat": "{{store_id}} {{packing}}"
    },
    {
     "expr": "rate(chunks_stored{instance=\"$node\"}[1h]) * 256 * 1024",
     "legendFormat": "[1h] {{store_id}} {{packing}}"
    }
   ]
  },
  {
   "title": "Average Sync Latency (seconds)",
   "type": "timeseries",
   "description": "Average latency for sync requests made to each peer",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(peer) (rate(http_client_get_chunk_duration_seconds_sum{instance=\"$node\", status_class=~\"success\"}[2m])) / sum by(peer) (rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\", status_class=~\"success\"}[2m]))",
     "legendFormat": "{{peer}}"
    },
    {
     "expr": "sum(rate(http_client_get_chunk_duration_seconds_sum{instance=\"$node\", status_class=~\"success\"}[2m])) / sum(rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\", status_class=~\"success\"}[2m]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Packing Rate (chunks / second)",
   "type": "timeseries",
   "description": "Packing operations performed per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by(packing) (rate(packing_duration_milliseconds_count{instance=\"$node\"}[2m]))",
     "legendFormat": "{{packing}}"
    },
    {
     "expr": "sum by(packing) (rate(packing_duration_milliseconds_count{instance=\"$node\"}[1h]))",
     "legendFormat": "[1h] {{packing}}"
    }
   ]
  }
 ]
}