{
 "title": "Mining",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "YOUR_NODE_ID" },
   { "name": "JOBNAME", "label": "job_name", "query": "${VAR_JOBNAME}" }
  ]
 },
 "panels": [
  {
   "title": "Read Rate vs. Ideal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"read\"}[5m]) / on(partition) avg_over_time(mining_rate{instance=\"$node\", type=\"ideal_read\"}[5m])",
     "legendFormat": "{{partition}} %  (5m)"
    }
   ]
  },
  {
   "title": "Hash Rate vs. Ideal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"hash\"}[5m]) / on(partition) avg_over_time(mining_rate{instance=\"$node\", type=\"ideal_hash\"}[5m])",
     "legendFormat": "{{partition}} %  (5m)"
    }
   ]
  },
  {
   "title": "Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"read\"}[5m])",
     "legendFormat": "{{partition}} actual (5m)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"ideal_read\"}[5m])",
     "legendFormat": "{{partition}} ideal (5m)"
    }
   ]
  },
  {
   "title": "Hash Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"hash\"}[5m])",
     "legendFormat": "{{partition}} actual (5m)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"ideal_hash\"}[5m])",
     "legendFormat": "{{partition}} ideal (5m)"
    }
   ]
  },
  { "title": "Debugging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Raw Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"raw_read\"}[5m])",
     "legendFormat": "{{partition}} (5m)"
    }
   ]
  },
  {
   "title": "Chunk Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mining_server_chunk_cache_size{instance=\"$node\", type=\"total\"}",
     "legendFormat": "Partition {{partition}}"
    },
    {
     "expr": "sum(mining_server_chunk_cache_size{instance=\"$node\", type=\"total\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mining Task Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "mining_server_task_queue_len{instance=\"$node\"}",
     "legendFormat": "{{task}}"
    },
    {
     "expr": "sum(mining_server_task_queue_len{instance=\"$node\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(avg_over_time(mining_server_task_queue_len{instance=\"$node\"}[1h]))",
     "legendFormat": "total avg (1h)"
    }
   ]
  },
  {
   "title": "Mining Task Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(mining_server_tasks{instance=\"$node\"}[2m])",
     "legendFormat": "{{task}}"
    },
    {
     "expr": "rate(mining_vdf_step{instance=\"$node\"}[2m])",
     "legendFormat": "vdf_step"
    },
    {
     "expr": "sum(rate(chunks_read{instance=\"$node\"}[2m]))",
     "legendFormat": "chunks_read"
    }
   ]
  }
 ]
}