{
 "title": "Syncing",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "YOUR_NODE_ID" },
   { "name": "peer", "label": "Peer", "query": { "query": "label_values(peer)" } },
   { "name": "JOBNAME", "label": "job_name", "query": "${VAR_JOBNAME}" }
  ]
 },
 "panels": [
  {
   "title": "Sync Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(peer) (rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\", peer=~\"$peer\"}[2m]))",
     "legendFormat": "{{peer}}"
    },
    {
     "expr": "sum(rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\", peer=~\"$peer\"}[2m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Chunks Received and Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(ar_http_request_duration_seconds_count{instance=\"$node\", route=\"/chunk2/{offset}\", http_method=\"GET\", status_class=\"success\"}[10m])) * 256 * 1024",
     "legendFormat": "Total Received"
    },
    {
     "expr": "rate(chunks_stored{instance=\"$node\"}[10m]) * 256 * 1024",
     "legendFormat": "{{store_id}} {{packing}} written"
    },
    {
     "expr": "sum(rate(chunks_stored{instance=\"$node\"}[10m]) * 256 * 1024)",
     "legendFormat": "Total Written"
    }
   ]
  },
  {
   "title": "Average Sync Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(peer) (rate(http_client_get_chunk_duration_seconds_sum{instance=\"$node\", peer=~\"$peer\", status_class=~\"success\"}[2m])) / sum by(peer) (rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\", peer=~\"$peer\", status_class=~\"success\"}[2m]))",
     "legendFormat": "{{peer}}"
    },
    {
     "expr": "sum(rate(http_client_get_chunk_duration_seconds_sum{instance=\"$node\", status_class=~\"success\"}[2m])) / sum(rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\", status_class=~\"success\"}[2m]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Sync Request Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (status_class) (rate(ar_http_request_duration_seconds_count{instance=\"$node\", route=\"/chunk2/{offset}\", http_method=\"GET\"}[10m])  * 256 * 1024)",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  { "title": "Debugging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Sync Interval Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sync_intervals_queue_size{instance=\"$node\"}",
     "legendFormat": "{{store_id}}"
    }
   ]
  },
  {
   "title": "Scheduled Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sync_tasks{instance=\"$node\", state=\"scheduled\"}",
     "legendFormat": "{{peer}}"
    },
    {
     "expr": "sum(sync_tasks{instance=\"$node\", state=\"scheduled\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Device Lock Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "device_lock_status{instance=\"$node\"} > -1",
     "legendFormat": "{{store_id}} {{mode}}"
    }
   ]
  },
  {
   "title": "Queued Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sync_tasks{instance=\"$node\", state=\"queued\"}",
     "legendFormat": "{{peer}}"
    },
    {
     "expr": "sum(sync_tasks{instance=\"$node\", state=\"queued\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk Pool Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "disk_pool_chunks_count{instance=\"$node\"}",
     "legendFormat": "disk_pool_chunks (# chunks)"
    },
    {
     "expr": "rate(disk_pool_processed_chunks{instance=\"$node\"}[2m])",
     "legendFormat": "disk_pool_processed_chunks (chunks/sec)"
    }
   ]
  }
 ]
}