{
 "title": "Arweave Debugging",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({job=\"$JOBNAME\"}, instance)"
    }
   },
   { "name": "cores", "query": "1" },
   { "name": "JOBNAME", "label": "job_name", "query": "${VAR_JOBNAME}" }
  ]
 },
 "panels": [
  {
   "title": "Mining",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Read Rate (MiB/s)",
     "type": "timeseries",
     "description": "The read rate for each partition as measured by the time it takes to read each 100MiB recall range. This value should not be impacted by any other bottlenecks in the mining pipeline and should pretty closely represent the observed read rate per partition.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "mining_rate{instance=\"$node\", type=\"raw_read\"}",
       "legendFormat": "{{partition}}"
      },
      {
       "expr": "sum(mining_rate{instance=\"$node\", type=\"raw_read\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Chunk Cache Size (# chunks)",
     "type": "timeseries",
     "description": "This panel shows how much of your configured chunk cache is being used (measured in 256 KiB chunks). You can change the chunk cache size limit using the `mining_server_chunk_cache_size_limit` launch parameter. The current limit is printed during node launch. \n\nIncreasing the chunk cache size limit can increase the memory used by your node while mining, but can also improve hashrate. The cache allows the miner to \"catch up\" if it falls behind temporarily due to other processes competing for resources. If your miner is consistently unable to keep up with new VDF steps, increasing the cache is unlikely to help (and my in fact hurt if it causes your node to exhaust available memory and go into swap).\n\nNote: you may see your actual chunk cache size exceed the limit occasionally. This is expected due to how the increments are recorded (increments of 800 per partition).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "mining_server_chunk_cache_size{instance=\"$node\"}",
       "legendFormat": "Partition {{partition}}"
      },
      {
       "expr": "sum(mining_server_chunk_cache_size{instance=\"$node\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Inbound Requests (# per second)",
     "type": "timeseries",
     "description": "HTTP requests your node receives per second.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(http_method, route) (rate(cowboy_requests_total{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Total Outbound Requests (# per second)",
     "type": "timeseries",
     "description": "Total number of HTTP requests your node makes to peers",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method) (rate(ar_http_request_duration_seconds_count{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Total Inbound Requests (total latency in seconds)",
     "type": "timeseries",
     "description": "Total latency of the HTTP requests your node receives",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by(http_method, route) (rate(cowboy_request_duration_seconds_sum{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Total Outbound Requests (total latency in seconds)",
     "type": "timeseries",
     "description": "Total latency of the HTTP requests your node makes to peers",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method) (rate(ar_http_request_duration_seconds_sum{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Total Inbound Requests (average latency in seconds)",
     "type": "timeseries",
     "description": "Average latency of the HTTP requests your node receives",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "(sum by(http_method, route) (rate(cowboy_request_duration_seconds_sum{instance=\"$node\"}[5m]))) /\n(sum by(http_method, route) (rate(cowboy_request_duration_seconds_count{instance=\"$node\"}[5m])))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    },
    {
     "title": "Total Outbound Requests (average latency in seconds)",
     "type": "timeseries",
     "description": "Average latency of the HTTP requests your node makes to peers",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(route, http_method) (rate(ar_http_request_duration_seconds_sum{instance=\"$node\"}[5m])) / sum by(route, http_method) (rate(ar_http_request_duration_seconds_count{instance=\"$node\"}[5m]))",
       "legendFormat": "{{http_method}} {{route}}"
      }
     ]
    }
   ]
  },
  { "title": "Debug Mode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Load / # Cores",
   "type": "timeseries",
   "description": "CPU load is measured per *virtual* core. If you have a 16-core CPU with Hyperthreading/SMT enabled, you will likely have 32 virtual cores. Set the dashboard variable appropriately to get a sense of your overall CPU load.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{instance=~\"$node\"}[5m])) without (kind) * 100) / $cores",
     "legendFormat": "CPU Load / # Cores"
    }
   ]
  },
  {
   "title": "Memory (bytes)",
   "type": "timeseries",
   "description": "Tracks the memory used by each erlang process.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(process_info{instance=\"$node\", type=~\"memory\", process!~\"processes|processes_used|total|system\"}, \"short_process\", \"$1\", \"process\", \"^(.{1,50}).*\")",
     "legendFormat": "{{short_process}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$node\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$node\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "process_max_resident_memory_bytes{instance=~\"$node\"}",
     "legendFormat": "Max Resident"
    },
    {
     "expr": "process_info{instance=\"$node\", type=~\"memory\", process=~\"processes|total\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Message Queue (# messages)",
   "type": "timeseries",
   "description": "Number of messages stored in each erlang process's message queue. Erlang processes can be though of as threads without shared memory. They send messages to communicate with each other. Before being processed a message is stored in a message queue. If a process's message queue is growing it means that process is receiving more messages than it can process and can help pinpoint the root cause of performance issues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(process) (process_info{instance=\"$node\", type=\"message_queue\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Reductions (#)",
   "type": "timeseries",
   "description": "Reductions are a measure of erlang process activity. The more reductions performed by a process, the more CPU cycles it has consumed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(process) (irate(process_info{instance=\"$node\", type=\"reductions\"}[2m]))",
     "legendFormat": "{{process}}"
    }
   ]
  }
 ]
}