{
 "title": "Sample Syncing/Packing Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": "YOUR-PROMETHEUS-INSTANCE" }
  ]
 },
 "panels": [
  {
   "title": "Total Chunks Written (in bytes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(chunks_stored{instance=\"$node\"}) * 256 * 1000",
     "legendFormat": "Chunks Written"
    }
   ]
  },
  {
   "title": "Sync Requests (# / second)",
   "type": "timeseries",
   "description": "GET /chunk2 requests sent per second to different peers. Each successful request downloads a chunk to your node.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(peer) (rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\"}[2m]))",
     "legendFormat": "{{peer}}"
    },
    {
     "expr": "sum(rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\"}[2m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Chunks Written (bytes / second)",
   "type": "timeseries",
   "description": "Each chunk written is assumed to be 256 KiB.\n\nNote: this may differ from your packing rate as each chunk written may need a different number of packing operations (0 to 2 depending on the format the chunk is received and the format it is written)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(chunks_stored{instance=\"$node\"}[2m]) * 256 * 1024",
     "legendFormat": "Bytes per second"
    },
    {
     "expr": "rate(chunks_stored{instance=\"$node\"}[1h]) * 256 * 1024",
     "legendFormat": "Smoothed"
    }
   ]
  },
  {
   "title": "Average Sync Latency (seconds)",
   "type": "timeseries",
   "description": "Average latency for sync requests made to each peer",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(peer) (rate(http_client_get_chunk_duration_seconds_sum{instance=\"$node\", status_class=~\"success\"}[2m])) / sum by(peer) (rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\", status_class=~\"success\"}[2m]))",
     "legendFormat": "{{peer}}"
    },
    {
     "expr": "sum(rate(http_client_get_chunk_duration_seconds_sum{instance=\"$node\", status_class=~\"success\"}[2m])) / sum(rate(http_client_get_chunk_duration_seconds_count{instance=\"$node\", status_class=~\"success\"}[2m]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Packing Rate (chunks / second)",
   "type": "timeseries",
   "description": "Packing operations performed per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(packing_duration_milliseconds_count{instance=\"$node\"}[2m]))",
     "legendFormat": "Chunks per second"
    },
    {
     "expr": "sum(rate(packing_duration_milliseconds_count{instance=\"$node\"}[1h]))",
     "legendFormat": "Smoothed"
    }
   ]
  }
 ]
}