{
 "title": "Arweave Miner",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": "YOUR-NODE-INSTANCE-LABEL" }
  ]
 },
 "panels": [
  {
   "title": "Read Rate",
   "type": "timeseries",
   "description": "This metric tracks the number of chunks read per second. 1 chunk is 256kib.\n\nThe protocol allows for up to 800 chunks per partition per VDF step to be read. That equates to roughly 200MiB/s per partition.\n\nWe recommend setting an alert at 0 MiB/s as that indicates the miner is no longer mining. You may also want to set an alert at some drop below an established baseline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"read\"}[5m])",
     "legendFormat": "{{partition}} (5m)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"read\"}[1h])",
     "legendFormat": "total (1h)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"read\"}[24h])",
     "legendFormat": "total (24h)"
    }
   ]
  },
  {
   "title": "Hash Rate",
   "type": "timeseries",
   "description": "This metric tracks the miner hashrate. The protocol allows for up to 400 H1 hashes and 400 H2 hashes per partition per VDF step. The metric also consider that an H1 hash is 100x less likely to result in a solution and scales the H1 hash count down accordingly. You can roughly interpret that as the protocol allowing 404 solution attempts (combination of H1 and H2 hashes) per partition per VDF step.\n\nNote: hashes are generated after chunks are read, so if your Read Rate chart shows a low read rate, your Hash Rate chart will also be lower.\n\nRe recommend setting an alert on 0 as that indicates your miner is no longer mining. You may also want to establish a baseline and set an alert if hashrate falls some amount below that baseline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"hash\"}[5m])",
     "legendFormat": "{{partition}} (5m)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"hash\"}[1h])",
     "legendFormat": "total (1h)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"hash\"}[24h])",
     "legendFormat": "total (24h)"
    },
    {
     "expr": "mining_rate{instance=\"$node\", partition=\"total\", type=\"hash\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Read Rate vs. Ideal",
   "type": "timeseries",
   "description": "This metric combines two values:\n1. Your miner's actual read rate\n2. The ideal read rate for an optimal miner with the same set of data sync and the same VDF speed.\n\nThe result is a percentage where 100% indicates you are mining at the ideal rate. The rate can exceed 100% for two reasons:\n1. The ideal and actual metrics are calculated on slightly different periods and so there might be some oscillation in the percentage.\n2. If your miner is mining as part of a coordinated mining set, the ideal rate is currently calculated assuming your miner is solo mining and doesn't take into account the hashes that your miner will perform for coordinated mining peers. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"read\"}[5m]) / on(partition) avg_over_time(mining_rate{instance=\"$node\", type=\"ideal_read\"}[5m])",
     "legendFormat": "{{partition}} (5m)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"read\"}[1h]) / on(partition) avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"ideal_read\"}[1h])",
     "legendFormat": "total (1h)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"read\"}[24h]) / on(partition) avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"ideal_read\"}[24h])",
     "legendFormat": "total (24h)"
    }
   ]
  },
  {
   "title": "Hash Rate vs. Ideal",
   "type": "timeseries",
   "description": "This metric combines two values:\n1. Your miner's actual hash rate\n2. The ideal hash rate for an optimal miner with the same set of data sync and the same VDF speed.\n\nThe result is a percentage where 100% indicates you are mining at the ideal rate. The rate can exceed 100% for two reasons:\n1. The ideal and actual metrics are calculated on slightly different periods and so there might be some oscillation in the percentage.\n2. If your miner is mining as part of a coordinated mining set, the ideal rate is currently calculated assuming your miner is solo mining and doesn't take into account the hashes that your miner will perform for coordinated mining peers. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", type=\"hash\"}[5m]) / on(partition) avg_over_time(mining_rate{instance=\"$node\", type=\"ideal_hash\"}[5m])",
     "legendFormat": "{{partition}} (5m)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"hash\"}[1h]) / on(partition) avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"ideal_hash\"}[1h])",
     "legendFormat": "total (1h)"
    },
    {
     "expr": "avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"hash\"}[24h]) / on(partition) avg_over_time(mining_rate{instance=\"$node\", partition=\"total\", type=\"ideal_hash\"}[24h])",
     "legendFormat": "total (24h)"
    },
    {
     "expr": "mining_rate{instance=\"$node\", partition=\"total\", type=\"hash\"} / on(partition) mining_rate{instance=\"$node\", partition=\"total\", type=\"ideal_hash\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "VDF Step Number",
   "type": "timeseries",
   "description": "This metric tracks the current VDF step number of the node - either calculated locally or received from a trusted VDF server. \n\nYou expect this number to increase roughly every second. We recommend starting with an alert that goes off if there are fewer than 200 steps in a 5-minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "vdf_step{instance=\"$node\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "description": "This metric tracks the height of the node's current tip node. We expect this number to increase roughly ever 2 minutes, but there can be substantial variation in the block time. We recommend alerting if you don't see a new block in 15 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "arweave_block_height{instance=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VDF Step Behind",
   "type": "timeseries",
   "description": "This metric tracks how many VDF steps the node is behind the last block it processed. A negative number means the node is *ahead* of the VDF step in the block.\n\nIf this number grows too large it can indicate that the node's VDF or VDF server is too slow or has fallen behind. We recommend setting an alert at 200, and adjusting as needed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "block_vdf_advance{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}